// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package loki

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node_Type int32

const (
	Node_DOCKER Node_Type = 0
	Node_K8S    Node_Type = 1
)

var Node_Type_name = map[int32]string{
	0: "DOCKER",
	1: "K8S",
}

var Node_Type_value = map[string]int32{
	"DOCKER": 0,
	"K8S":    1,
}

func (x Node_Type) String() string {
	return proto.EnumName(Node_Type_name, int32(x))
}

func (Node_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0, 0}
}

type StateTrick_Type int32

const (
	StateTrick_NODE_DOWN   StateTrick_Type = 0
	StateTrick_NODE_RESTRT StateTrick_Type = 1
)

var StateTrick_Type_name = map[int32]string{
	0: "NODE_DOWN",
	1: "NODE_RESTRT",
}

var StateTrick_Type_value = map[string]int32{
	"NODE_DOWN":   0,
	"NODE_RESTRT": 1,
}

func (x StateTrick_Type) String() string {
	return proto.EnumName(StateTrick_Type_name, int32(x))
}

func (StateTrick_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2, 0}
}

type Node struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Node_Type `protobuf:"varint,2,opt,name=type,proto3,enum=loki.Node_Type" json:"type,omitempty"`
	NetworkId            string    `protobuf:"bytes,3,opt,name=networkId,proto3" json:"networkId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetType() Node_Type {
	if m != nil {
		return m.Type
	}
	return Node_DOCKER
}

func (m *Node) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

type TrickPolicy struct {
	Delay                int64    `protobuf:"varint,1,opt,name=delay,proto3" json:"delay,omitempty"`
	Keep                 int64    `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	Interval             int64    `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrickPolicy) Reset()         { *m = TrickPolicy{} }
func (m *TrickPolicy) String() string { return proto.CompactTextString(m) }
func (*TrickPolicy) ProtoMessage()    {}
func (*TrickPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *TrickPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrickPolicy.Unmarshal(m, b)
}
func (m *TrickPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrickPolicy.Marshal(b, m, deterministic)
}
func (m *TrickPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrickPolicy.Merge(m, src)
}
func (m *TrickPolicy) XXX_Size() int {
	return xxx_messageInfo_TrickPolicy.Size(m)
}
func (m *TrickPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_TrickPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_TrickPolicy proto.InternalMessageInfo

func (m *TrickPolicy) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *TrickPolicy) GetKeep() int64 {
	if m != nil {
		return m.Keep
	}
	return 0
}

func (m *TrickPolicy) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type StateTrick struct {
	Nodes                []*Node         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Type                 StateTrick_Type `protobuf:"varint,2,opt,name=type,proto3,enum=loki.StateTrick_Type" json:"type,omitempty"`
	Policy               *TrickPolicy    `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StateTrick) Reset()         { *m = StateTrick{} }
func (m *StateTrick) String() string { return proto.CompactTextString(m) }
func (*StateTrick) ProtoMessage()    {}
func (*StateTrick) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *StateTrick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTrick.Unmarshal(m, b)
}
func (m *StateTrick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTrick.Marshal(b, m, deterministic)
}
func (m *StateTrick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTrick.Merge(m, src)
}
func (m *StateTrick) XXX_Size() int {
	return xxx_messageInfo_StateTrick.Size(m)
}
func (m *StateTrick) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTrick.DiscardUnknown(m)
}

var xxx_messageInfo_StateTrick proto.InternalMessageInfo

func (m *StateTrick) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *StateTrick) GetType() StateTrick_Type {
	if m != nil {
		return m.Type
	}
	return StateTrick_NODE_DOWN
}

func (m *StateTrick) GetPolicy() *TrickPolicy {
	if m != nil {
		return m.Policy
	}
	return nil
}

type NodeResource struct {
	Cpu                  int64    `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeResource) Reset()         { *m = NodeResource{} }
func (m *NodeResource) String() string { return proto.CompactTextString(m) }
func (*NodeResource) ProtoMessage()    {}
func (*NodeResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *NodeResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeResource.Unmarshal(m, b)
}
func (m *NodeResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeResource.Marshal(b, m, deterministic)
}
func (m *NodeResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResource.Merge(m, src)
}
func (m *NodeResource) XXX_Size() int {
	return xxx_messageInfo_NodeResource.Size(m)
}
func (m *NodeResource) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResource.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResource proto.InternalMessageInfo

func (m *NodeResource) GetCpu() int64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *NodeResource) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type ResourceTrick struct {
	Nodes                []*Node       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Resource             *NodeResource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Policy               *TrickPolicy  `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResourceTrick) Reset()         { *m = ResourceTrick{} }
func (m *ResourceTrick) String() string { return proto.CompactTextString(m) }
func (*ResourceTrick) ProtoMessage()    {}
func (*ResourceTrick) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *ResourceTrick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTrick.Unmarshal(m, b)
}
func (m *ResourceTrick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTrick.Marshal(b, m, deterministic)
}
func (m *ResourceTrick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTrick.Merge(m, src)
}
func (m *ResourceTrick) XXX_Size() int {
	return xxx_messageInfo_ResourceTrick.Size(m)
}
func (m *ResourceTrick) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTrick.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTrick proto.InternalMessageInfo

func (m *ResourceTrick) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ResourceTrick) GetResource() *NodeResource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceTrick) GetPolicy() *TrickPolicy {
	if m != nil {
		return m.Policy
	}
	return nil
}

// TODO
type NetworkTrick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkTrick) Reset()         { *m = NetworkTrick{} }
func (m *NetworkTrick) String() string { return proto.CompactTextString(m) }
func (*NetworkTrick) ProtoMessage()    {}
func (*NetworkTrick) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *NetworkTrick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkTrick.Unmarshal(m, b)
}
func (m *NetworkTrick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkTrick.Marshal(b, m, deterministic)
}
func (m *NetworkTrick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkTrick.Merge(m, src)
}
func (m *NetworkTrick) XXX_Size() int {
	return xxx_messageInfo_NetworkTrick.Size(m)
}
func (m *NetworkTrick) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkTrick.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkTrick proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("loki.Node_Type", Node_Type_name, Node_Type_value)
	proto.RegisterEnum("loki.StateTrick_Type", StateTrick_Type_name, StateTrick_Type_value)
	proto.RegisterType((*Node)(nil), "loki.Node")
	proto.RegisterType((*TrickPolicy)(nil), "loki.TrickPolicy")
	proto.RegisterType((*StateTrick)(nil), "loki.StateTrick")
	proto.RegisterType((*NodeResource)(nil), "loki.NodeResource")
	proto.RegisterType((*ResourceTrick)(nil), "loki.ResourceTrick")
	proto.RegisterType((*NetworkTrick)(nil), "loki.NetworkTrick")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x6e, 0xa3, 0x40,
	0x10, 0xc6, 0xbd, 0x06, 0x73, 0xf6, 0xe0, 0x3f, 0xdc, 0xe8, 0xee, 0x84, 0x2e, 0x29, 0x10, 0x91,
	0x22, 0xbb, 0xa1, 0x20, 0x8d, 0xfb, 0xd8, 0x45, 0x64, 0x09, 0x47, 0x0b, 0x52, 0xca, 0xc8, 0x81,
	0x2d, 0x10, 0xd8, 0x8b, 0x30, 0x76, 0xc4, 0x3b, 0xe4, 0x51, 0xf2, 0x90, 0x11, 0xc3, 0xc6, 0x76,
	0xba, 0xa4, 0xdb, 0xe1, 0xfb, 0xcd, 0xec, 0xf7, 0x0d, 0x0b, 0xe6, 0x56, 0x26, 0x22, 0xf7, 0x8a,
	0x52, 0x56, 0x12, 0xf5, 0x5c, 0x66, 0xa9, 0x7b, 0x04, 0x3d, 0x90, 0x89, 0xc0, 0x31, 0x74, 0xd3,
	0xc4, 0x66, 0x0e, 0x9b, 0x0e, 0x78, 0x37, 0x4d, 0xf0, 0x06, 0xf4, 0xaa, 0x2e, 0x84, 0xdd, 0x75,
	0xd8, 0x74, 0xec, 0x4f, 0xbc, 0x06, 0xf6, 0x1a, 0xd2, 0x8b, 0xea, 0x42, 0x70, 0x12, 0xf1, 0x1a,
	0x06, 0x3b, 0x51, 0xbd, 0xca, 0x32, 0x7b, 0x48, 0x6c, 0x8d, 0x7a, 0xcf, 0x1f, 0xdc, 0x2b, 0xd0,
	0x1b, 0x16, 0x01, 0x8c, 0xc5, 0xfa, 0x7e, 0xb5, 0xe4, 0x56, 0x07, 0x7f, 0x81, 0xb6, 0x9a, 0x87,
	0x16, 0x73, 0x43, 0x30, 0xa3, 0x32, 0x8d, 0xb3, 0x47, 0x99, 0xa7, 0x71, 0x8d, 0x7f, 0xa0, 0x97,
	0x88, 0x7c, 0x53, 0x93, 0x03, 0x8d, 0xb7, 0x05, 0x22, 0xe8, 0x99, 0x10, 0x05, 0x99, 0xd0, 0x38,
	0x9d, 0xf1, 0x3f, 0xf4, 0xd3, 0x5d, 0x25, 0xca, 0xe3, 0x26, 0xa7, 0x2b, 0x35, 0x7e, 0xaa, 0xdd,
	0x77, 0x06, 0x10, 0x56, 0x9b, 0x4a, 0xd0, 0x68, 0x74, 0xa0, 0xb7, 0x93, 0x89, 0xd8, 0xdb, 0xcc,
	0xd1, 0xa6, 0xa6, 0x0f, 0xe7, 0x10, 0xbc, 0x15, 0x70, 0xf6, 0x25, 0xe5, 0xdf, 0x16, 0x38, 0x4f,
	0xb8, 0xcc, 0x3a, 0x03, 0xa3, 0x20, 0xaf, 0x74, 0xab, 0xe9, 0xff, 0x6e, 0xe1, 0x8b, 0x10, 0x5c,
	0x01, 0xee, 0xad, 0x0a, 0x3e, 0x82, 0x41, 0xb0, 0x5e, 0x2c, 0x9f, 0x17, 0xeb, 0xa7, 0xc0, 0xea,
	0xe0, 0x04, 0x4c, 0x2a, 0xf9, 0x32, 0x8c, 0x78, 0x64, 0x31, 0x77, 0x0e, 0x43, 0x32, 0x23, 0xf6,
	0xf2, 0x50, 0xc6, 0x02, 0x2d, 0xd0, 0xe2, 0xe2, 0xa0, 0x56, 0xd0, 0x1c, 0xf1, 0x1f, 0x18, 0x5b,
	0xb1, 0x95, 0x65, 0xad, 0x56, 0xa0, 0x2a, 0xf7, 0x8d, 0xc1, 0xe8, 0xb3, 0xed, 0xbb, 0x59, 0x3d,
	0xe8, 0x97, 0xaa, 0x85, 0xa6, 0x99, 0x3e, 0x5e, 0x40, 0x4a, 0xe1, 0x27, 0xe6, 0x27, 0x81, 0xc7,
	0x30, 0x0c, 0xda, 0xdf, 0x4e, 0xea, 0x8b, 0x41, 0x2f, 0xec, 0xee, 0x23, 0x00, 0x00, 0xff, 0xff,
	0x8c, 0x2f, 0x74, 0xc2, 0x70, 0x02, 0x00, 0x00,
}
